### ISSUE TITLE
Schematic?

### ISSUE THREAD

**Issue by shakram02** [seky2205/Hacking-dell-charger#2]
Would you please provide a schematic for the Arduino circuit ? :) 
Thanks!

**Comment by ghost** [comment]
I will post it soon

**Comment by ghost** [comment]
You need to go in between charger and laptop because communication start the moment that charger is plugged in.. Code is not supporting communication reset (it can be easily implemented) because my experience shows that it is working ok this way.

The best way would be to get charger with 3 pin connector and just cut wires and solder in between connector and charger brick

![dellhack](https://user-images.githubusercontent.com/9872263/26992230-ee72d12a-4d5d-11e7-8d9b-cac5b8938622.png)

**Comment by shakram02** [comment]
Thank you so much, I suggest putting the schematic in the readme just in case, thanks again for your efforts
